name: Build Pi Stream EADK External App

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            git \
            gcc-arm-none-eabi \
            binutils-arm-none-eabi

      - name: Clone NumWorks Epsilon for EADK
        run: |
          git clone --depth 1 https://github.com/numworks/epsilon.git

      - name: Build EADK external app
        run: |
          # Build the Pi Stream EADK app
          make clean
          make pi_stream.nwa

      - name: Verify .nwa file
        run: |
          ls -la pi_stream.nwa
          file pi_stream.nwa
          echo "NWA file size: $(stat -c%s pi_stream.nwa) bytes"

      - name: Upload .nwa artifact
        uses: actions/upload-artifact@v4
        with:
          name: pi-stream-eadk-nwa
          path: pi_stream.nwa


