name: Build Pi Stream EADK External App

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ARM toolchain and Node.js
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            git \
            gcc-arm-none-eabi \
            binutils-arm-none-eabi \
            libnewlib-arm-none-eabi \
            libstdc++-arm-none-eabi-newlib \
            nodejs \
            npm

      - name: Build EADK external app
        run: |
          # Build the Pi Stream EADK app using proper nwlink
          make clean
          make build

      - name: Verify .nwa file
        run: |
          ls -la output/pi_stream.nwa
          file output/pi_stream.nwa
          echo "NWA file size: $(stat -c%s output/pi_stream.nwa) bytes"

      - name: Upload .nwa artifact
        uses: actions/upload-artifact@v4
        with:
          name: pi-stream-eadk-nwa
          path: output/pi_stream.nwa


